1:
  role: leader
  neighbors:
    - neighbor_id: 2
      bearing: [-1.0, 0.0]
    - neighbor_id: 3
      bearing: [0.0, -1.0]
    - neighbor_id: 4
      bearing: [-0.70710678, -0.70710678]

2:
  role: leader
  neighbors:
    - neighbor_id: 1
      bearing: [1.0, 0.0]
    - neighbor_id: 4
      bearing: [0.0, -1.0]
    - neighbor_id: 3
      bearing: [0.70710678, -0.70710678]

3:
  role: follower
  neighbors:
    - neighbor_id: 1
      bearing: [0.0, 1.0]
    - neighbor_id: 4
      bearing: [-1.0, 0.0]
    - neighbor_id: 2
      bearing: [-0.70710678, 0.70710678]

4:
  role: follower
  neighbors:
    - neighbor_id: 2
      bearing: [0.0, 1.0]
    - neighbor_id: 3
      bearing: [1.0, 0.0]
    - neighbor_id: 1
      bearing: [0.70710678, 0.70710678]
